  sonar.projectKey=intrusion-detection-ml
  sonar.projectName=ML Intrusion Detection System
  sonar.projectVersion=1.0
  sonar.sources=.
  sonar.exclusions=**/venv/**,**/.venv/**,**/env/**,**/.env/**,**/.vscode/**,**/.elasticbeanstalk/**,**/__pycache__/**,**/*.pkl,**/*.ipynb,**/*.csv
  sonar.host.url=http://localhost:9000




# sqp_05e0138c18549b889642fffe2365b7ed074060af
